### ISSUE TITLE
README's typescript API link is down.

### ISSUE THREAD

**Issue by DJunge-w** [Daninet/gmp-wasm#7]
Hi! I am using the gmp-wasm in typescript, the link to typescript API on README seems not working.(https://paka.dev/npm/gmp-wasm/v/0.9.4)

**Comment by Daninet** [comment]
Hey. Thank you for the bug report. I fixed it.

https://paka.dev/npm/gmp-wasm/v/1.0.1
https://daninet.github.io/gmp-wasm/
